<?php

namespace Database\Seeders;

use App\Models\EmailTemplate;
use Illuminate\Database\Seeder;

class EmailTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name'    => 'Applicant Approved',
                'slug'    => 'applicant_approved',
                'subject' => 'Your Application Has Been Approved – {{ system_name }}',
                'body'    => $this->approvedBody(),
                'is_active' => true,
            ],
            [
                'name'    => 'Applicant Rejected',
                'slug'    => 'applicant_rejected',
                'subject' => 'Update on Your Application – {{ system_name }}',
                'body'    => $this->rejectedBody(),
                'is_active' => true,
            ],
        ];

        foreach ($templates as $template) {
            EmailTemplate::updateOrCreate(
                ['slug' => $template['slug']],
                $template
            );
        }
    }

    private function approvedBody(): string
    {
        return <<<'HTML'
            <p>Dear <strong>{{ applicant_name }}</strong>,</p>

            <p>
                Greetings from <strong>{{ system_name }}</strong>.
            </p>

            <p>
                We are pleased to inform you that your application has been
                <strong style="color:#198754;">APPROVED</strong>.
            </p>

            <div style="background:#f8f9fa;border-left:4px solid #198754;padding:16px 18px;margin:24px 0;border-radius:6px;">
                <h3 style="margin:0 0 12px;font-size:16px;color:#198754;">
                    Application Details
                </h3>

                <table role="presentation" cellpadding="4" cellspacing="0" width="100%" style="font-size:14px;">
                    <tr>
                        <td width="180"><strong>Applicant</strong></td>
                        <td>{{ applicant_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>Category</strong></td>
                        <td>{{ applicant_category }}</td>
                    </tr>
                    <tr>
                        <td><strong>Place of Examination</strong></td>
                        <td>{{ place_of_examination }}</td>
                    </tr>
                    <tr>
                        <td><strong>Date Submitted</strong></td>
                        <td>{{ application_date }}</td>
                    </tr>
                    <tr>
                        <td><strong>Status</strong></td>
                        <td style="color:#198754;font-weight:bold;">
                            {{ verification_status }}
                        </td>
                    </tr>
                </table>
            </div>

            <p>
                Please present the QR Code below during verification or upon request by the examination personnel.
                This QR Code is unique to your application and will be used to validate your approved registration.
            </p>

            {{ verification_qr }}

            <div style="background:#fff8e1;border:1px solid #ffe082;border-radius:8px;padding:14px;margin-top:20px;">
                <strong>Important Reminders</strong>
                <ul style="margin:10px 0 0 18px;padding:0;">
                    <li>Keep this email for your records.</li>
                    <li>Do not share your QR Code with other applicants.</li>
                    <li>Present the QR Code together with a valid identification card during verification.</li>
                    <li>If your QR Code cannot be scanned, contact the administrator immediately.</li>
                </ul>
            </div>

            <p style="margin-top:24px;">
                Congratulations! We look forward to seeing you on your scheduled examination.
            </p>

            <p>
                Respectfully,<br>
                <strong>{{ system_name }}</strong>
            </p>

            <hr style="border:none;border-top:1px solid #e9ecef;margin:28px 0;">

            <p style="font-size:12px;color:#6c757d;text-align:center;">
                This is an automated email generated by <strong>{{ system_name }}</strong>.<br>
                Please do not reply directly to this message.
            </p>
            HTML;
    }

    private function rejectedBody(): string
    {
        return <<<'HTML'
<p>Dear {{ applicant_name }},</p>
<p>Thank you for submitting your application to {{ system_name }}.</p>
<p>After careful review, we regret to inform you that your application has been <strong>rejected</strong>.</p>
<p><strong>Application Details</strong></p>
<ul>
<li>Category: {{ applicant_category }}</li>
<li>Place of Examination: {{ place_of_examination }}</li>
<li>Date Submitted: {{ application_date }}</li>
</ul>
<p><strong>Remarks:</strong><br>{{ remarks }}</p>
<p>If you have questions, please contact our office during business hours.</p>
<p>Respectfully,<br>{{ system_name }}</p>
<p><em>This is an automated message. Please do not reply directly to this email.</em></p>
HTML;
    }
}
