<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $subject }}</title>
</head>

<body
    style="margin:0;padding:0;background:#f4f6f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#212529;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:32px 16px;">
        <tr>
            <td align="center">
                <table role="presentation"
                    style="
                    width:100%;
                    max-width:640px;
                    background:#ffffff;
                    border-radius:14px;
                    overflow:hidden;
                    border:1px solid #e9ecef;">

                    {{-- Header --}}
                    <tr>
                        <td
                            style="
                            background:#0d6efd;
                            color:#ffffff;
                            padding:28px 36px;">

                            <div
                                style="
                                font-size:22px;
                                font-weight:700;">
                                {{ $systemName }}
                            </div>

                            <div
                                style="
                                margin-top:6px;
                                font-size:14px;
                                opacity:.9;">
                                Automated Notification
                            </div>

                        </td>
                    </tr>

                    {{-- Subject --}}
                    <tr>
                        <td style="padding:28px 36px 18px">

                            <h2
                                style="
                                margin:0;
                                font-size:22px;
                                font-weight:700;
                                color:#212529;">
                                {{ $subject }}
                            </h2>

                        </td>
                    </tr>

                    <tr>
                        <td>
                            <hr
                                style="
                                border:none;
                                border-top:1px solid #e9ecef;
                                margin:0;">
                        </td>
                    </tr>

                    {{-- Email Body --}}
                    <tr>
                        <td
                            style="
                            padding:32px 36px;
                            font-size:15px;
                            line-height:1.8;
                            color:#495057;">

                            {!! $body !!}

                        </td>
                    </tr>

                    <tr>
                        <td>
                            <hr
                                style="
                                border:none;
                                border-top:1px solid #e9ecef;
                                margin:0;">
                        </td>
                    </tr>

                    {{-- Footer --}}
                    <tr>
                        <td
                            style="
                            background:#f8f9fa;
                            padding:24px 36px;
                            color:#6c757d;
                            font-size:13px;">

                            <strong>{{ $systemName }}</strong><br>

                            This email was automatically generated by the system.
                            Please do not reply to this message.

                            <br><br>

                            Generated on {{ now()->format('F d, Y h:i A') }}

                            <br><br>

                            &copy; {{ now()->year }} {{ $systemName }}.
                            All Rights Reserved.

                        </td>
                    </tr>

                </table>

            </td>
        </tr>
    </table>

</body>

</html>
